# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1817a6c1c07db25f57109193c704c3913b24308a29d7ffb086c0e2fd7ed3c40f4a6822c07c169381dc53c71b50c695dd400a79d805fe3dda1e59003878f9f803

test:
  secret_key_base: 5853d92586820d90a5dcc4a27676ced13be96cec8692ab38afd8b9ea5f0e813875b255d6c91ac44d99631c9a2bdbf24e389fb2d1c919fb37d69dbea2762a4b82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
